# flake8: noqa

"""
    Umweltbundesamt: Rigoletto API

    API Description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.0"

# import ApiClient
from deutschland.rigoletto.api_client import ApiClient

# import Configuration
from deutschland.rigoletto.configuration import Configuration

# import exceptions
from deutschland.rigoletto.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
