"""
    Umweltbundesamt: Rigoletto API

    API Description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.rigoletto.api.default_api import DefaultApi  # noqa: E501

from deutschland import rigoletto


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_tabelle_export_tabelle_get(self):
        """Test case for export_tabelle_export_tabelle_get

        Export Tabelle  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
